apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: operator-minio-operator-csr
spec:
  request: <copy base64 encoded curve.csr here>
  signerName: kubernetes.io/kubelet-serving
  expirationSeconds: 604800 #extend here for 1 year long
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:minio-operator
  - system:authenticated
  - system:nodes
  usages:
	- "digital signature"
	- "key encipherment"
	- "server auth"
  username: system:serviceaccount:minio-operator:minio-operator