apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: myminio-csr
spec:
  request: <base-64-coded-csr>
  signerName: kubernetes.io/kubelet-serving
  expirationSeconds: 604800 #extend here for 1 year long
  groups:
  - system:serviceaccounts
  - system:serviceaccounts:minio-operator
  - system:authenticated
  - system:nodes
  usages:
    - "digital signature"
    - "key encipherment"
    - "server auth"
  username: system:serviceaccount:minio-operator:minio-operator