---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    service: metastore-env
  name: metastore-env
  namespace: metastore
data:
  K8S_NAMESPACE: "metastore"
  S3_BUCKET: "lakehouse"
  HIVE_S3_BUCKET: "lakehouse/db"
  S3_ENDPOINT: "http://myminio-hl.minio-tenant.svc.cluster.local:9000"
  HIVE_SSL_ENABLED: "false"
  HIVE_USE_INSTANCE_CREDENTIALS: "false"
  HIVE_HOST: "hive-service"
  HIVE_PORT: "9083"
  HIVE_METASTORE_SERVER_MIN_THREADS: "1"
  HIVE_METASTORE_SERVER_MAX_THREADS: "100"
  POSTGRES_URL: "jdbc:postgresql://postgres-postgresql:5432/hivemetastore?sslmode=require&amp;sslrootcert=/etc/postgres/ca.crt&amp;sslcert=/etc/postgres/tls.crt&amp;sslkey=/etc/postgres/tls.key"
  POSTGRES_DB: "hivemetastore"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres-postgresql"
  POSTGRES_PORT: "5432"


---
