---
apiVersion: v1
kind: Service
metadata:
  name: hive-service
  namespace: metastore
spec:
  type: ClusterIP
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
    - name: "10000"
      port: 10000
      targetPort: 10000
  selector:
    app: hive-metastore
---
