apiVersion: v1
kind: Secret
metadata:
  name: kes-configuration
  namespace: minio-tenant
type: Opaque
stringData:
  server-config.yaml: |-
    version: v1
    address: :7373
    keystore:
      vault:
        endpoint: "http://vault.default.svc.cluster.local:8200"
        prefix: "my-minio"
        approle:
          id: "<role-id>"
          secret: "<secret-id>"
