apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: minio-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minio-deployment
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
