apiVersion: v1
kind: Pod
metadata:
  name: pgdump-check
  namespace: metastore
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c", "ls /backup/pgdump && sleep 3600"]
      volumeMounts:
        - name: pgdump-volume
          mountPath: /backup
  volumes:
    - name: pgdump-volume
      persistentVolumeClaim:
        claimName: postgres-postgresql-pgdumpall  # Replace with your actual PVC name
  restartPolicy: Never
