apiVersion: v1
kind: Pod
metadata:
  name: non-root-pod
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 2000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: httpd-logs
      mountPath: /usr/local/apache2/logs   # Make the logs directory writable
  volumes:
  - name: httpd-logs
    emptyDir: {}
