apiVersion: v1
kind: Pod
metadata:
  name: readonly-pod
spec:
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: httpd-logs
      mountPath: /usr/local/apache2/logs   # Make the logs directory writable
  volumes:
  - name: httpd-logs
    emptyDir: {}